apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../../va/nfv/sriov/
  # - https://github.com/openstack-k8s-operators/architecture/va/nfv/sriov?ref=main
  ## It's possible to replace ../../../va/nfv/sriov/ with a git checkout URL as per:
  ## https://github.com/kubernetes-sigs/kustomize/blob/master/examples/remoteBuild.md

resources:
  - service-values.yaml

replacements:
# Neutron control plane SRIOV customization
- source:
    kind: ConfigMap
    name: service-values
    fieldPath: data.neutron.customServiceConfig
  targets:
  - select:
      kind: OpenStackControlPlane
    fieldPaths:
    - spec.neutron.template.customServiceConfig
    options:
      create: true
# Nova control plane SRIOV customization
- source:
    kind: ConfigMap
    name: service-values
    fieldPath: data.nova.scheduler.customServiceConfig
  targets:
  - select:
      kind: OpenStackControlPlane
    fieldPaths:
    - spec.nova.template.schedulerServiceTemplate.customServiceConfig
    options:
      create: true
