---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../../../va/nvidia-mdev/edpm-post-driver/deployment
  # - https://github.com/openstack-k8s-operators/architecture/va/nvidia-mdev/edpm-post-driver/deployment?ref=main
  ## It's possible to replace ../../../../../va/nvidia-mdev/edpm-post-driver/deployment/ with a git checkout URL as per:
  ## https://github.com/kubernetes-sigs/kustomize/blob/master/examples/remoteBuild.md

resources:
  - values.yaml

replacements:
  - source:
      kind: ConfigMap
      name: edpm-nodeset-post-driver-values
      fieldPath: data.servicesOverride
    targets:
      - select:
          kind: OpenStackDataPlaneDeployment
        fieldPaths:
          - spec.servicesOverride
        options:
          create: true
  - source:
      kind: ConfigMap
      name: edpm-nodeset-post-driver-values
      fieldPath: data.ansibleExtraVars
    targets:
      - select:
          kind: OpenStackDataPlaneDeployment
        fieldPaths:
          - spec.ansibleExtraVars
        options:
          create: true
  - source:
      kind: ConfigMap
      name: edpm-nodeset-post-driver-values
      fieldPath: data.deployment.name
    targets:
      - select:
          kind: OpenStackDataPlaneDeployment
        fieldPaths:
          - metadata.name
        options:
          create: true
